spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
server:
  port: 8080
logging:
  level:
    root: warn
    xyz:
      catuns:
        edupulse:
          engagement: info
